steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'gcr.io/$PROJECT_ID/gcpdevops', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'gcr.io/$PROJECT_ID/gcpdevops']

  # Deploy container image to gke
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args: 
    - run
    - --filename=gke.yaml
    - --image=gcr.io/$PROJECT_ID/gcpdevops
    - --location=asia-east1-a
    - --cluster=gcp-project-gke
    - --namespace=gcp-devops-prod